config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resource :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :events
  resources :invites
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :creator, class_name: "User", foreign_key: :user_id
  has_many :invites, inverse_of: 'event'
  has_many :attendees, through: :invites

  scope :past,     -> { where('date < ?', Time.current).order(date: :desc) }
  scope :upcoming, -> { where('date > ?', Time.current).order(date: :asc) }

  def show_date
    date.strftime("%A, %B %-d %l:%M %P")
  end

end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :attendee,       class_name: "User",  foreign_key: :user_id
  belongs_to :attended_event, class_name: "Event", foreign_key: :event_id
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_many :invites
  has_many :attended_events, through: :invites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @user = User.find_by(name: session[:name])
    @upcoming_events = Event.upcoming
    @previous_events = Event.past
  end

  def create
    @user = User.find_by(name: session[:name])
    @event = @user.events.build(event_params)
    if @event.save
      flash[:success] = "Event created!"
      redirect_to @event
    else
      flash[:danger] = "Something is wrong!"
      redirect_back(fallback_location: root_url)
    end
  end

  def show
    @user = User.find_by(name: session[:name])
    @event = Event.find_by(id: params[:id])
  end

  private

    def event_params
      params.require(:event).permit(:name, :description, :date)
    end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

  def index
    @user = User.find_by(name: session[:name])
    @invites = Invite.find_by(user_id: @user.id)
  end

  def new
    @user = User.find_by(name: session[:name])
    @users = User.all
  end

  def create
    @event = Event.find(params[:invite][:event_id])
    @invite = @event.invites.build(invite_params)
    if @invite.save
      redirect_to @event
    else
      render "new"
    end
  end

  def show
    @user = User.find_by(name: session[:name])
  end

  def update
    @invite = Invite.find(params[:id])
    @invite.update_attribute(:accepted, true)
    if @invite.save
      puts "Yes"
      redirect_to "/invites"
    else
      puts "No"
      redirect_to root_url
    end
  end

  private

    def invite_params
      params.require(:invite).permit(:user_id, :event_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name].downcase)
    if @user
      session[:name] = @user.name
      flash[:success] = "Logged in."
      redirect_to @user
    else
      flash[:danger] = "Name not registered."
      render "new"
    end
  end

  def destroy
    params[:session] = nil
    session[:name] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User created!"
      redirect_to @user
    else
      flash[:danger] = "User was not created!"
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @event = @user.events.build
    @invite = @event.invites.build
    @upcoming_events = @user.events.upcoming
    @previous_events = @user.events.past
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "User deleted"
    redirect_to signup_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :email)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event_form.html.erb
<%= form_for(@event) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :date %>
  <%= f.datetime_select :date, datetime_separator: "", order: [:month, :day, :year], start_year: Time.current.year, prompt: { month: "Month", day: "Day", year: "Year" } %>
  <%= f.submit "Submit" %>
<% end %>

app/views/events/index.html.erb
<h1>Upcoming Events</h1>
<% @upcoming_events.each do |event| %>
  <hr>
  <h3><%= event.name %></h3>
  <p><%= event.description %></p>
  <p>Starting <%= event.show_date %></p>
  <p>Created by <%= event.creator.name %></p>
<% end %>
<h1>Previous Events</h1>
<% @previous_events.each do |event| %>
  <hr>
  <h3><%= event.name %></h3>
  <p><%= event.description %></p>
  <p>Started <%= event.show_date %></p>
  <p>Created by <%= event.creator.name %></p>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.description %></h1>
<p>Attending: </p>
<% @event.attendees.each do |attendee| %>
  <p><%= attendee.name %></p>
<% end %>
<p>Created by <%= @event.creator.name %></p>

app/views/invites/index.html.erb
<% @user.invites.each do |invite| %>
  <% unless invite.accepted %>
    <p><i><%= invite.event.creator.name %></i> invited you to attend <b><%= invite.event.name %></b></p>
    <p>Would you like to attend?</p>
    <%= form_for :invite, url: invite_path(invite), method: :put do |f| %>
      <%= f.submit "Attending" %>
    <% end %>
  <% end %>
<% end %>

app/views/invites/new.html.erb
<h1><%= @event.name %></h1>
<p><%= @event.description %></p>
<p><%= @event.show_date %></p>
<% @users.each do |user| %>
  <span><%= user.name %> <%# link_to 'invite', invite_path %></span>
<% end %>

app/views/layouts/_nav.html.erb
<header>
  <ul>
    <% if session[:name] %>
      <li><%= link_to 'home', root_path %></li>

      <li><%= link_to 'profile', user_path(@user) %></li>
      <li><%= link_to 'invites', invites_path %></li>
      <li><%= link_to 'logout', logout_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'signin', signin_path %> or <%= link_to 'signup', signup_path%></li>
    <% end %>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Create new user</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<%= render 'events/event_form' if session[:name] == @user.name %>
<h2>Upcoming Events:</h2>
<% @upcoming_events.each do |e| %>
  <h2><%= e.name %></h2>
  <p><%= e.description %></p>
  <span><%= e.show_date %></span>
  <%= form_for(@invite) do |f| %>
    <%= f.hidden_field :event_id, value: e.id %>
    <%= f.collection_select :user_id, User.where.not(id: @user.id), :id, :name, prompt: "Select User", selected: "" %> 
    <%= f.submit "Send Invite" %>   
  <% end %>
<% end if @upcoming_events.any?%>
<h2>Previous Events:</h2>
<% @previous_events.each do |e| %>
  <h2><%= e.name %></h2>
  <p><%= e.description %></p>
  <span><%= e.show_date %></span>
<% end if @previous_events.any? %>
<h2>Attending:</h2>
<% @user.attended_events.each do |event| %>
  <% event.invites.each do |invite| %>
    <% if invite.accepted %>
      <p><%= event.description%></p>
      <p>Hosted by <%= event.creator.name %></p>
    <% end %>
  <% end %>
<% end %>
<% if session[:name] == @user.name %>
  <%= link_to 'delete user', @user, method: :delete %>
<% end %>